/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppValoresRouteImport } from './routes/_app.valores'
import { Route as AppUsuariosRouteImport } from './routes/_app.usuarios'
import { Route as AppTutorialRouteImport } from './routes/_app.tutorial'
import { Route as AppLogsRouteImport } from './routes/_app.logs'
import { Route as AppLixeiraRouteImport } from './routes/_app.lixeira'
import { Route as AppItbiRouteImport } from './routes/_app.itbi'
import { Route as AppFollowUpRouteImport } from './routes/_app.follow-up'
import { Route as AppFinanceiroRouteImport } from './routes/_app.financeiro'
import { Route as AppEscritoriosRouteImport } from './routes/_app.escritorios'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAdminTabelasRouteImport } from './routes/_app.admin-tabelas'
import { Route as AppOrcamentosIndexRouteImport } from './routes/_app.orcamentos.index'
import { Route as AppOrcamentosNovoRouteImport } from './routes/_app.orcamentos.novo'
import { Route as AppOrcamentosIdRouteImport } from './routes/_app.orcamentos.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppValoresRoute = AppValoresRouteImport.update({
  id: '/valores',
  path: '/valores',
  getParentRoute: () => AppRoute,
} as any)
const AppUsuariosRoute = AppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppTutorialRoute = AppTutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsRoute = AppLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppRoute,
} as any)
const AppLixeiraRoute = AppLixeiraRouteImport.update({
  id: '/lixeira',
  path: '/lixeira',
  getParentRoute: () => AppRoute,
} as any)
const AppItbiRoute = AppItbiRouteImport.update({
  id: '/itbi',
  path: '/itbi',
  getParentRoute: () => AppRoute,
} as any)
const AppFollowUpRoute = AppFollowUpRouteImport.update({
  id: '/follow-up',
  path: '/follow-up',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppEscritoriosRoute = AppEscritoriosRouteImport.update({
  id: '/escritorios',
  path: '/escritorios',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminTabelasRoute = AppAdminTabelasRouteImport.update({
  id: '/admin-tabelas',
  path: '/admin-tabelas',
  getParentRoute: () => AppRoute,
} as any)
const AppOrcamentosIndexRoute = AppOrcamentosIndexRouteImport.update({
  id: '/orcamentos/',
  path: '/orcamentos/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrcamentosNovoRoute = AppOrcamentosNovoRouteImport.update({
  id: '/orcamentos/novo',
  path: '/orcamentos/novo',
  getParentRoute: () => AppRoute,
} as any)
const AppOrcamentosIdRoute = AppOrcamentosIdRouteImport.update({
  id: '/orcamentos/$id',
  path: '/orcamentos/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin-tabelas': typeof AppAdminTabelasRoute
  '/dashboard': typeof AppDashboardRoute
  '/escritorios': typeof AppEscritoriosRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/follow-up': typeof AppFollowUpRoute
  '/itbi': typeof AppItbiRoute
  '/lixeira': typeof AppLixeiraRoute
  '/logs': typeof AppLogsRoute
  '/tutorial': typeof AppTutorialRoute
  '/usuarios': typeof AppUsuariosRoute
  '/valores': typeof AppValoresRoute
  '/orcamentos/$id': typeof AppOrcamentosIdRoute
  '/orcamentos/novo': typeof AppOrcamentosNovoRoute
  '/orcamentos/': typeof AppOrcamentosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin-tabelas': typeof AppAdminTabelasRoute
  '/dashboard': typeof AppDashboardRoute
  '/escritorios': typeof AppEscritoriosRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/follow-up': typeof AppFollowUpRoute
  '/itbi': typeof AppItbiRoute
  '/lixeira': typeof AppLixeiraRoute
  '/logs': typeof AppLogsRoute
  '/tutorial': typeof AppTutorialRoute
  '/usuarios': typeof AppUsuariosRoute
  '/valores': typeof AppValoresRoute
  '/orcamentos/$id': typeof AppOrcamentosIdRoute
  '/orcamentos/novo': typeof AppOrcamentosNovoRoute
  '/orcamentos': typeof AppOrcamentosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/admin-tabelas': typeof AppAdminTabelasRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/escritorios': typeof AppEscritoriosRoute
  '/_app/financeiro': typeof AppFinanceiroRoute
  '/_app/follow-up': typeof AppFollowUpRoute
  '/_app/itbi': typeof AppItbiRoute
  '/_app/lixeira': typeof AppLixeiraRoute
  '/_app/logs': typeof AppLogsRoute
  '/_app/tutorial': typeof AppTutorialRoute
  '/_app/usuarios': typeof AppUsuariosRoute
  '/_app/valores': typeof AppValoresRoute
  '/_app/orcamentos/$id': typeof AppOrcamentosIdRoute
  '/_app/orcamentos/novo': typeof AppOrcamentosNovoRoute
  '/_app/orcamentos/': typeof AppOrcamentosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin-tabelas'
    | '/dashboard'
    | '/escritorios'
    | '/financeiro'
    | '/follow-up'
    | '/itbi'
    | '/lixeira'
    | '/logs'
    | '/tutorial'
    | '/usuarios'
    | '/valores'
    | '/orcamentos/$id'
    | '/orcamentos/novo'
    | '/orcamentos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin-tabelas'
    | '/dashboard'
    | '/escritorios'
    | '/financeiro'
    | '/follow-up'
    | '/itbi'
    | '/lixeira'
    | '/logs'
    | '/tutorial'
    | '/usuarios'
    | '/valores'
    | '/orcamentos/$id'
    | '/orcamentos/novo'
    | '/orcamentos'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/admin-tabelas'
    | '/_app/dashboard'
    | '/_app/escritorios'
    | '/_app/financeiro'
    | '/_app/follow-up'
    | '/_app/itbi'
    | '/_app/lixeira'
    | '/_app/logs'
    | '/_app/tutorial'
    | '/_app/usuarios'
    | '/_app/valores'
    | '/_app/orcamentos/$id'
    | '/_app/orcamentos/novo'
    | '/_app/orcamentos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/valores': {
      id: '/_app/valores'
      path: '/valores'
      fullPath: '/valores'
      preLoaderRoute: typeof AppValoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/usuarios': {
      id: '/_app/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AppUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tutorial': {
      id: '/_app/tutorial'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof AppTutorialRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logs': {
      id: '/_app/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AppLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lixeira': {
      id: '/_app/lixeira'
      path: '/lixeira'
      fullPath: '/lixeira'
      preLoaderRoute: typeof AppLixeiraRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/itbi': {
      id: '/_app/itbi'
      path: '/itbi'
      fullPath: '/itbi'
      preLoaderRoute: typeof AppItbiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/follow-up': {
      id: '/_app/follow-up'
      path: '/follow-up'
      fullPath: '/follow-up'
      preLoaderRoute: typeof AppFollowUpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro': {
      id: '/_app/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/escritorios': {
      id: '/_app/escritorios'
      path: '/escritorios'
      fullPath: '/escritorios'
      preLoaderRoute: typeof AppEscritoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin-tabelas': {
      id: '/_app/admin-tabelas'
      path: '/admin-tabelas'
      fullPath: '/admin-tabelas'
      preLoaderRoute: typeof AppAdminTabelasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orcamentos/': {
      id: '/_app/orcamentos/'
      path: '/orcamentos'
      fullPath: '/orcamentos/'
      preLoaderRoute: typeof AppOrcamentosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orcamentos/novo': {
      id: '/_app/orcamentos/novo'
      path: '/orcamentos/novo'
      fullPath: '/orcamentos/novo'
      preLoaderRoute: typeof AppOrcamentosNovoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orcamentos/$id': {
      id: '/_app/orcamentos/$id'
      path: '/orcamentos/$id'
      fullPath: '/orcamentos/$id'
      preLoaderRoute: typeof AppOrcamentosIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminTabelasRoute: typeof AppAdminTabelasRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEscritoriosRoute: typeof AppEscritoriosRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppFollowUpRoute: typeof AppFollowUpRoute
  AppItbiRoute: typeof AppItbiRoute
  AppLixeiraRoute: typeof AppLixeiraRoute
  AppLogsRoute: typeof AppLogsRoute
  AppTutorialRoute: typeof AppTutorialRoute
  AppUsuariosRoute: typeof AppUsuariosRoute
  AppValoresRoute: typeof AppValoresRoute
  AppOrcamentosIdRoute: typeof AppOrcamentosIdRoute
  AppOrcamentosNovoRoute: typeof AppOrcamentosNovoRoute
  AppOrcamentosIndexRoute: typeof AppOrcamentosIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminTabelasRoute: AppAdminTabelasRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEscritoriosRoute: AppEscritoriosRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppFollowUpRoute: AppFollowUpRoute,
  AppItbiRoute: AppItbiRoute,
  AppLixeiraRoute: AppLixeiraRoute,
  AppLogsRoute: AppLogsRoute,
  AppTutorialRoute: AppTutorialRoute,
  AppUsuariosRoute: AppUsuariosRoute,
  AppValoresRoute: AppValoresRoute,
  AppOrcamentosIdRoute: AppOrcamentosIdRoute,
  AppOrcamentosNovoRoute: AppOrcamentosNovoRoute,
  AppOrcamentosIndexRoute: AppOrcamentosIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
